/**
 * Manifest of slugs that have a per-post og:image PNG generated by
 * `scripts/generate-blog-og-images.ts` — SEO roadmap A4.
 *
 * AUTO-GENERATED — do not edit by hand. Run
 * `npx tsx scripts/generate-blog-og-images.ts` to regenerate after
 * touching `BLOG_POSTS`.
 *
 * The generator writes 1200×630 PNGs to
 * `public/og/blog/<slug>.png`. We mirror the slug list here so
 * `seoForBlogPost` can pick the per-post file without a filesystem
 * check at runtime.
 */
const BLOG_OG_SLUGS: ReadonlySet<string> = new Set([
  "buy-adobe-creative-cloud-iran",
  "buy-adobe-firefly-iran",
  "buy-ajelix-iran",
  "buy-apple-music-iran",
  "buy-autoshorts-ai-iran",
  "buy-babbel-iran",
  "buy-canva-pro-iran",
  "buy-chatgpt-plus-iran",
  "buy-claude-pro-iran",
  "buy-crunchyroll-iran",
  "buy-deepl-iran",
  "buy-dr-fone-iran",
  "buy-dreamina-iran",
  "buy-dropbox-plus-iran",
  "buy-duolingo-super-iran",
  "buy-easymusic-iran",
  "buy-elevenlabs-iran",
  "buy-flexclip-iran",
  "buy-gemini-advanced-iran",
  "buy-hbo-iran",
  "buy-hitpaw-iran",
  "buy-homestyler-iran",
  "buy-icloud-iran",
  "buy-ideogram-iran",
  "buy-ilovesong-iran",
  "buy-jetbrains-iran",
  "buy-leonardo-iran",
  "buy-lingq-iran",
  "buy-linkedin-premium-iran",
  "buy-magoosh-iran",
  "buy-midjourney-iran",
  "buy-nightcafe-iran",
  "buy-perplexity-iran",
  "buy-pika-iran",
  "buy-pluralsight-iran",
  "buy-proton-iran",
  "buy-prowritingaid-iran",
  "buy-quillbot-iran",
  "buy-rephrasy-iran",
  "buy-rosetta-stone-iran",
  "buy-shutterstock-iran",
  "buy-suno-iran",
  "buy-surfer-seo-iran",
  "buy-talkingavatar-iran",
  "buy-visual-electric-iran",
])

export function hasPerBlogOgImage(slug: string): boolean {
  return BLOG_OG_SLUGS.has(slug)
}

export function perBlogOgImagePath(slug: string): string {
  return `/og/blog/${slug}.png`
}
