import {
  Sparkles,
  Image as ImageIcon,
  Video,
  Music,
  Pen,
  Code,
  Palette,
  Briefcase,
  PlayCircle,
  Headphones,
  GraduationCap,
  Cloud,
  MessageSquare,
  BarChart3,
  Layers,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  image: ImageIcon,
  video: Video,
  music: Music,
  pen: Pen,
  code: Code,
  palette: Palette,
  briefcase: Briefcase,
  play: PlayCircle,
  headphones: Headphones,
  graduation: GraduationCap,
  cloud: Cloud,
  message: MessageSquare,
  chart: BarChart3,
}

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return Layers
  return map[name] ?? Layers
}

const colors = [
  '#d4a853',
  '#2ec4b6',
  '#9b5de5',
  '#00b4d8',
  '#f77f00',
  '#06d6a0',
  '#118ab2',
  '#ef476f',
  '#e63946',
  '#f4a261',
  '#7b2cbf',
  '#22c55e',
  '#3b82f6',
  '#fb7185',
]

// Stable, hand-picked anchor color per category (used for accents, glows, chips).
// Anything not listed falls back to a deterministic hash → palette pick so we
// never crash if new categories are added on the backend.
const categoryColors: Record<string, string> = {
  'ai-assistants': '#9b5de5',
  'ai-image': '#ef476f',
  'ai-video': '#e63946',
  'ai-voice-music': '#06d6a0',
  'ai-writing-seo': '#d4a853',
  'developer-tools': '#3b82f6',
  'design-creative': '#fb7185',
  'productivity-work': '#f4a261',
  streaming: '#e63946',
  music: '#7b2cbf',
  education: '#118ab2',
  'cloud-storage': '#00b4d8',
  'social-communication': '#f77f00',
  'business-marketing': '#22c55e',
}

export function colorForCategory(slug: string): string {
  if (categoryColors[slug]) return categoryColors[slug]
  let h = 0
  for (let i = 0; i < slug.length; i++) {
    h = (h * 31 + slug.charCodeAt(i)) >>> 0
  }
  return colors[h % colors.length]
}

// Hero image per category. Kept in lockstep with public/images/categories/<slug>.jpg
// generated by scripts/generate_category_images.py.
const categoryImages: Record<string, string> = {
  'ai-assistants': '/images/categories/ai-assistants.jpg',
  'ai-image': '/images/categories/ai-image.jpg',
  'ai-video': '/images/categories/ai-video.jpg',
  'ai-voice-music': '/images/categories/ai-voice-music.jpg',
  'ai-writing-seo': '/images/categories/ai-writing-seo.jpg',
  'developer-tools': '/images/categories/developer-tools.jpg',
  'design-creative': '/images/categories/design-creative.jpg',
  'productivity-work': '/images/categories/productivity-work.jpg',
  streaming: '/images/categories/streaming.jpg',
  music: '/images/categories/music.jpg',
  education: '/images/categories/education.jpg',
  'cloud-storage': '/images/categories/cloud-storage.jpg',
  'social-communication': '/images/categories/social-communication.jpg',
  'business-marketing': '/images/categories/business-marketing.jpg',
}

const FALLBACK_IMAGE =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 12"><rect width="16" height="12" fill="%2313141a"/></svg>'

export function imageForCategory(slug: string): string {
  return categoryImages[slug] ?? FALLBACK_IMAGE
}
