import {
  Sparkles,
  Image as ImageIcon,
  Video,
  Music,
  Pen,
  Code,
  Palette,
  Briefcase,
  PlayCircle,
  Headphones,
  GraduationCap,
  Cloud,
  MessageSquare,
  BarChart3,
  Layers,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  image: ImageIcon,
  video: Video,
  music: Music,
  pen: Pen,
  code: Code,
  palette: Palette,
  briefcase: Briefcase,
  play: PlayCircle,
  headphones: Headphones,
  graduation: GraduationCap,
  cloud: Cloud,
  message: MessageSquare,
  chart: BarChart3,
}

export function iconFor(name: string | null | undefined): LucideIcon {
  if (!name) return Layers
  return map[name] ?? Layers
}

// Editorial Ivory: a single graphite tone for every category.
// Differentiation now lives in the icon glyph and the category title — not in
// per-category color halos, glows, or chip tints.
const INK_GRAPHITE = '#5b5755'

export function colorForCategory(slug: string): string {
  void slug
  return INK_GRAPHITE
}

// Hero image per category. Kept in lockstep with public/images/categories/<slug>.jpg
// generated by scripts/generate_category_images.py.
const categoryImages: Record<string, string> = {
  'ai-assistants': '/images/categories/ai-assistants.jpg',
  'ai-image': '/images/categories/ai-image.jpg',
  'ai-video': '/images/categories/ai-video.jpg',
  'ai-voice-music': '/images/categories/ai-voice-music.jpg',
  'ai-writing-seo': '/images/categories/ai-writing-seo.jpg',
  'developer-tools': '/images/categories/developer-tools.jpg',
  'design-creative': '/images/categories/design-creative.jpg',
  'productivity-work': '/images/categories/productivity-work.jpg',
  streaming: '/images/categories/streaming.jpg',
  music: '/images/categories/music.jpg',
  education: '/images/categories/education.jpg',
  'cloud-storage': '/images/categories/cloud-storage.jpg',
  'social-communication': '/images/categories/social-communication.jpg',
  'business-marketing': '/images/categories/business-marketing.jpg',
}

const FALLBACK_IMAGE =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 12"><rect width="16" height="12" fill="%2313141a"/></svg>'

export function imageForCategory(slug: string): string {
  return categoryImages[slug] ?? FALLBACK_IMAGE
}
