/**
 * Audit `Product` JSON-LD across the entire marketplace catalogue.
 *
 * Run: `npm run audit:product` (also useful pre-deploy in CI).
 *
 * The script materialises `productLd` for every active service in
 * `public/data/marketplace.json`, optionally enriched with the per-service
 * detail/FAQ/long-description files generated by `npm run enrich`. It
 * verifies the four fields Google's Product rich-result requires
 * (`name`, `description`, `image`, `offers`) plus the trust-signal
 * fields we explicitly added to lift Pikart out of "minimum viable":
 *
 *   - sku              (must be a non-empty string)
 *   - brand.name       (must be a non-empty string)
 *   - category         (must be a non-empty string)
 *   - description      (≥ 200 chars; warn if < 1500)
 *   - offers           (must be present)
 *   - audience.geographicArea  (Iran)
 *
 * Exits non-zero when any service is missing a hard-required field so
 * CI can gate the build. Soft warnings (description < 1500 chars) are
 * reported but do NOT fail the build — the operator should expand the
 * descriptions iteratively as the SEO content roadmap progresses.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { productLd } from '../src/lib/jsonld'
import type {
  Category,
  Plan,
  Service,
  ServiceDetail,
} from '../src/lib/data'

function findCheapestPlan(plans: Plan[]): Plan | null {
  return (
    [...plans]
      .filter((p) => p.priceIrt != null && p.isActive)
      .sort((a, b) => (a.priceIrt ?? 0) - (b.priceIrt ?? 0))[0] ?? null
  )
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const marketplacePath = resolve(repoRoot, 'public/data/marketplace.json')
const servicesDir = resolve(repoRoot, 'public/data/services')

type Marketplace = {
  services: Service[]
  categories: Category[]
  plans: Plan[]
}

if (!existsSync(marketplacePath)) {
  console.error(`[audit-product] missing ${marketplacePath}`)
  process.exit(2)
}

const marketplace = JSON.parse(readFileSync(marketplacePath, 'utf8')) as Marketplace
const categories = new Map(marketplace.categories.map((c) => [c.id, c]))
const plansByService = new Map<string, Plan[]>()
for (const plan of marketplace.plans) {
  if (!plan.isActive) continue
  const list = plansByService.get(plan.serviceId) ?? []
  list.push(plan)
  plansByService.set(plan.serviceId, list)
}

const detailsBySlug = new Map<string, ServiceDetail>()
if (existsSync(servicesDir)) {
  for (const f of readdirSync(servicesDir)) {
    if (!f.endsWith('.json')) continue
    const slug = f.replace(/\.json$/, '')
    try {
      const raw = readFileSync(resolve(servicesDir, f), 'utf8')
      detailsBySlug.set(slug, JSON.parse(raw) as ServiceDetail)
    } catch (err) {
      console.warn(`[audit-product] bad detail file ${f}:`, err)
    }
  }
}

type Issue = {
  level: 'error' | 'warn'
  slug: string
  field: string
  message: string
}

const issues: Issue[] = []
let checked = 0
let withLongDesc = 0
const descLengths: number[] = []

for (const service of marketplace.services) {
  if (!service.slug) continue
  checked++

  const category = service.categoryId ? categories.get(service.categoryId) : undefined
  const plans = plansByService.get(service.id) ?? []
  const cheapest = findCheapestPlan(plans) ?? null
  const detail = detailsBySlug.get(service.slug) ?? null

  const ld = productLd({
    service,
    category,
    plans,
    cheapest,
    path: `/s/${service.slug}`,
    longDescription: detail?.descriptionFa,
  }) as Record<string, unknown>

  // ---- hard-required fields (block CI on miss) ----
  if (!ld.name || typeof ld.name !== 'string' || !ld.name.trim()) {
    issues.push({ level: 'error', slug: service.slug, field: 'name', message: 'missing or empty' })
  }
  if (!ld.sku || typeof ld.sku !== 'string' || !ld.sku.trim()) {
    issues.push({ level: 'error', slug: service.slug, field: 'sku', message: 'missing or empty' })
  }
  if (!ld.category || typeof ld.category !== 'string' || !ld.category.trim()) {
    issues.push({
      level: 'error',
      slug: service.slug,
      field: 'category',
      message: `missing (categoryId=${service.categoryId ?? '<null>'})`,
    })
  }
  const brand = ld.brand as Record<string, unknown> | undefined
  if (!brand || typeof brand.name !== 'string' || !(brand.name as string).trim()) {
    issues.push({ level: 'error', slug: service.slug, field: 'brand.name', message: 'missing or empty' })
  }
  if (!ld.image) {
    issues.push({ level: 'error', slug: service.slug, field: 'image', message: 'missing logoUrl' })
  }
  if (!ld.offers) {
    issues.push({ level: 'error', slug: service.slug, field: 'offers', message: 'missing offers (no priced plans?)' })
  }

  // ---- description length: warn-only ----
  const desc = typeof ld.description === 'string' ? ld.description : ''
  descLengths.push(desc.length)
  if (desc.length === 0) {
    issues.push({ level: 'error', slug: service.slug, field: 'description', message: 'empty' })
  } else if (desc.length < 200) {
    issues.push({
      level: 'warn',
      slug: service.slug,
      field: 'description',
      message: `${desc.length} chars (< 200; below Google's recommended minimum)`,
    })
  } else if (desc.length < 1500) {
    issues.push({
      level: 'warn',
      slug: service.slug,
      field: 'description',
      message: `${desc.length} chars (< 1500; expand to compete with license-market.ir)`,
    })
  } else {
    withLongDesc++
  }

  // ---- offers shape sanity ----
  const offers = ld.offers as Record<string, unknown> | undefined
  if (offers) {
    const offerType = offers['@type']
    if (offerType !== 'Offer' && offerType !== 'AggregateOffer') {
      issues.push({
        level: 'error',
        slug: service.slug,
        field: 'offers.@type',
        message: `unexpected ${String(offerType)}`,
      })
    }
    if (!offers.priceCurrency) {
      issues.push({ level: 'error', slug: service.slug, field: 'offers.priceCurrency', message: 'missing' })
    }
    if (!offers.availability) {
      issues.push({ level: 'error', slug: service.slug, field: 'offers.availability', message: 'missing' })
    }
    if (!offers.url) {
      issues.push({ level: 'error', slug: service.slug, field: 'offers.url', message: 'missing' })
    }
  }
}

// ---- report -------------------------------------------------------------

const errors = issues.filter((i) => i.level === 'error')
const warns = issues.filter((i) => i.level === 'warn')

console.log(`[audit-product] checked ${checked} active services`)
console.log(
  `[audit-product] description lengths: min=${Math.min(...descLengths)} max=${Math.max(...descLengths)} avg=${Math.round(descLengths.reduce((a, b) => a + b, 0) / Math.max(1, descLengths.length))}`,
)
console.log(`[audit-product] services with description >= 1500 chars: ${withLongDesc}/${checked}`)
console.log(`[audit-product] errors: ${errors.length}, warnings: ${warns.length}`)

if (errors.length > 0) {
  console.error('\n[audit-product] ERRORS:')
  for (const e of errors.slice(0, 50)) {
    console.error(`  - ${e.slug} :: ${e.field} :: ${e.message}`)
  }
  if (errors.length > 50) console.error(`  ... and ${errors.length - 50} more`)
}

if (warns.length > 0) {
  console.warn('\n[audit-product] WARNINGS (top 20):')
  for (const w of warns.slice(0, 20)) {
    console.warn(`  - ${w.slug} :: ${w.field} :: ${w.message}`)
  }
  if (warns.length > 20) console.warn(`  ... and ${warns.length - 20} more`)
}

if (errors.length > 0) {
  process.exit(1)
}
console.log('\n[audit-product] OK — no hard-required Product fields are missing.')
